# Generated by Django 4.2.6 on 2023-12-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_maintenancetask_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='task',
        ),
    ]
