# Generated by Django 4.2.6 on 2023-12-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
        ('system', '0003_remove_workorder_asset_remove_workorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder'),
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
