# Generated by Django 4.2.6 on 2023-12-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_maintenancehistory_work_order_delete_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
