# Generated by Django 4.2.6 on 2023-12-29 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('asset_to_be_serviced', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('engineer_feed', models.CharField(choices=[('Attending', 'Attending'), ('InProgress', 'In Progress'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('user_feed', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
