# Generated by Django 4.2.6 on 2023-12-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='Name',
            field=models.CharField(default='brian', max_length=100),
            preserve_default=False,
        ),
    ]
