# Generated by Django 4.2.6 on 2023-12-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_maintenancehistory_work_order_delete_workorder'),
        ('services', '0002_servicerequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='asset_to_be_serviced',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.asset'),
        ),
    ]
