# Generated by Django 4.2.6 on 2024-01-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('services', '0003_alter_servicerequest_asset_to_be_serviced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_demanded', models.PositiveIntegerField()),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sparepart')),
            ],
            options={
                'unique_together': {('service_request', 'spare_part')},
            },
        ),
    ]
